---
abstract: 'to convert from unixtime to date suitably'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Test::More: '0.88'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-FromUnixtime
provides:
  App::FromUnixtime:
    file: lib/App/FromUnixtime.pm
    version: '0.09'
requires:
  Config::CmdRC: '0'
  Getopt::Long: '0'
  IO::Interactive::Tiny: '0'
  POSIX: '0'
  Pod::Usage: '0'
  perl: '5.008001'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://github.com/bayashi/App-FromUnixtime/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/App-FromUnixtime
version: '0.09'
